@startuml

box "drv-ns16550"
    participant "デバイス\nファイル管理" as filemng
end box
participant "MLib"               as mlib
participant "mvfs\n(ライブラリ)" as libmvfs

activate mlib

filemng <- mlib: Task12( グローバルFD )
activate filemng

filemng -> libmvfs: デバイスファイルopen応答(失敗)
activate libmvfs
filemng <-- libmvfs:
deactivate libmvfs

filemng --> mlib:
deactivate filemng

@enduml
