@startuml

box "drv-ns16550"
    participant "デバイス\nファイル管理" as filemng
end box
participant "MLib"               as mlib
participant "mvfs\n(ライブラリ)" as libmvfs

activate libmvfs
ref over filemng, libmvfs
    デバイスファイル操作要求待ち合わせ
end ref

filemng <- libmvfs: デバイスファイルwrite要求
activate filemng

filemng -> filemng: グローバルFD\nデバイス識別番号変換

alt デバイス識別番号 == COM1(/serial1)
    filemng -> mlib: 状態遷移実行( serial1, write要求 )
    activate mlib
    ref over filemng, mlib
        Task32
    end ref
    filemng <-- mlib:
    deactivate mlib

else デバイス識別番号 == COM2(/serial2)
    filemng -> mlib: 状態遷移実行( serial2, write要求 )
    activate mlib
    ref over filemng, mlib
        Task32
    end ref
    filemng <-- mlib:
    deactivate mlib

else
    filemng -> libmvfs: デバイスファイルwrite応答(失敗)
    activate libmvfs
    filemng <-- libmvfs:
    deactivate libmvfs

end alt

filemng --> libmvfs:
deactivate filemng

@enduml

