@startuml

participant "MochiKernel\n(ライブラリ)" as libmk
box "drv-ns16550"
    participant "メイン"   as main
    participant "転送制御" as txctrl
end box
participant "MLib" as mlib

activate main
ref over main
    メイン
    初期化
end ref

main -> txctrl: 初期化
activate txctrl

txctrl -> mlib: COM1用スピンロック初期化
activate mlib
txctrl <-- mlib:
deactivate mlib

txctrl -> mlib: COM2用スピンロック初期化
activate mlib
txctrl <-- mlib:
deactivate mlib

main <-- txctrl:
deactivate txctrl

@enduml
